import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const books = [
  {
    title: "Harry Potter e a Pedra Filosofal",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2000-01-01T00:00:00Z"),
    isbn: "9788532511010",
    language: "Português",
    pageCount: 264,
    coverImage: "/HarryPotterPedraFilosofal",
    genres: ["Fantasia", "Infantojuvenil"],
    description: `A vida de Harry Potter é um verdadeiro labirinto de desprezo até que, no seu décimo primeiro aniversário, recebe uma carta inusitada: foi aceito na Escola de Magia e Bruxaria de Hogwarts. Um mundo mágico, aventureiro e cheio de mistérios se desdobra — dos jogos de Quadribol às ameaças de um bruxo que supostamente morreu há anos. Essa obra inaugura uma jornada épica de coragem, amizade, descoberta de identidade e enfrentamento de um mal que transcende gerações.`,
    averageRating: 5.0,
    ratingsCount: 56,
    synopsis: `Harry vive com os tios e morava num armário sob a escada. No seu décimo primeiro aniversário, descobre seu verdadeiro legado — e recebe uma carta de Hogwarts. Até então invisível ao mundo, o garoto bruxo é convidado a frequentar a escola de magia mais famosa do mundo. Ali, aprenderá feitiços, enfrentará desafios e descobrirá seu papel crucial na luta contra as forças das trevas.`,
    authorBio: `J. K. Rowling é a autora britânica da série Harry Potter, criada no início dos anos 1990 e publicada entre 1997 e 2007. A saga transformou-se em fenômeno global, transcendendo os livros — com filmes, parques temáticos e uma fundação beneficente, Lumos.`
  },
  {
    title: "Harry Potter e a Câmara Secreta",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2000-01-01T00:00:00Z"),
    isbn: "9788532511669",
    language: "Português",
    pageCount: 252,
    coverImage: "/HarryPotterCamaraSecreta",
    genres: ["Fantasia", "Infantojuvenil"],
    description: `No seu segundo ano em Hogwarts, Harry é alertado pelo elfo Dobby sobre um perigo iminente. Em seguida, alunos começam a ser petrificados e segredos antigos vêm à tona. Sob a tensão, Harry descobre fragmentos de sua história e seu vínculo com Voldemort.`,
    averageRating: 4.8,
    ratingsCount: 45,
    synopsis: `Após um verão difícil com os tios, Harry volta à escola enquanto estranhas petrificações abalavam Hogwarts. Com Rony e Hermione ao seu lado, ele investiga segredos enterrados — e desafia um legado sombrio que ressurge dos corredores da escola.`,
    authorBio: `(Mesmo bio do anterior; reiterado para cada obra, caso deseje consistência.)`
  },
  {
    title: "Harry Potter e o Prisioneiro de Azkaban",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2000-01-01T00:00:00Z"),
    isbn: "9788532512062",
    language: "Português",
    pageCount: 348,
    coverImage: "/HarryPotterPrisioneiroAzkaban",
    genres: ["Fantasia", "Infantojuvenil"],
    description: `No terceiro ano de Hogwarts, Harry descobre que Sirius Black, perigoso prisioneiro de Azkaban, pode estar à solta — e talvez ligada à tragédia que tirou a vida de seus pais. Dementadores, segredos e reviravoltas emergem nessa trama de suspense e descoberta.`,
    averageRating: 4.9,
    ratingsCount: 52,
    synopsis: `Chocado por saber que Sirius Black pode querer vingar-se, Harry enfrenta Dementadores, segredos de família e a verdade sobre aquela noite que o tornou órfão. A chegada de um novo professor, Lupin, revela mais do que o esperado — e uma amizade, uma lealdade e uma escolha crucial emergem.`,
    authorBio: `(Mesmo bio)`
  },
  {
    title: "Harry Potter e o Cálice de Fogo",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2001-06-01T00:00:00Z"),
    isbn: "9788532513083",
    language: "Português",
    pageCount: 480,
    coverImage: "/HarryPotterCaliceFogo",
    genres: ["Fantasia", "Infantojuvenil", "Aventura"],
    description: `Harry é misteriosamente inscrito no Torneio Tribruxo, competição perigosa onde jovens bruxos enfrentam dragões, labirintos e desafios mortais. Enquanto compete, gris mantece sombras que ameaçam ressurgir e espalhar o terror.`,
    averageRating: 4.9,
    ratingsCount: 47,
    synopsis: `Entre desafios mágicos e dilemas crescentes, Harry descobre que lutar por glória não basta — seu destino e o do mundo bruxo precisam ser enfrentados. A competição revela alianças, traições e o retorno de uma face que o tempo queria esquecer.`,
    authorBio: `(Mesmo bio)`
  },
  {
    title: "Harry Potter e a Ordem da Fênix",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2003-07-01T00:00:00Z"),
    isbn: "9788532514080",
    language: "Português",
    pageCount: 656,
    coverImage: "/HarryPotterOrdemFenix",
    genres: ["Fantasia", "Infantojuvenil", "Aventura", "Drama"],
    description: `O mundo bruxo vive negação sobre o retorno de Voldemort. Harry e seus aliados enfrentam a descrença do Ministério da Magia, ganham aliados na Ordem da Fênix e criam força própria: a Armada de Dumbledore.`,
    averageRating: 4.8,
    ratingsCount: 50,
    synopsis: `Sem acreditar na ameaça crescente, o Ministério pune Harry e Dumbledore. Diante da repressão, ele lidera seus amigos numa resistência inédita — que é, ao mesmo tempo, curso de defesa mágica e chama de esperança.`,
    authorBio: `(Mesmo bio)`
  },
  {
    title: "Harry Potter e o Enigma do Príncipe",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2005-08-01T00:00:00Z"),
    isbn: "9788532515124",
    language: "Português",
    pageCount: 608,
    coverImage: "/HarryPotterEnigmaPrincipe",
    genres: ["Fantasia", "Infantojuvenil", "Mistério"],
    description: `Em busca de entender Voldemort, Harry encontra um livro antigo que pertencia ao misterioso Príncipe Mestiço — repleto de anotações preciosas. Revelações e tragédias aproximam-no da verdade e do sacrifício iminente.`,
    averageRating: 4.8,
    ratingsCount: 49,
    synopsis: `A adolescência se mistura com a urgência da guerra. Enquanto aprende e ama, Harry descobre fragmentos do passado de Voldemort — e se prepara para o futuro sem Dumbledore.`,
    authorBio: `(Mesmo bio)`
  },
  {
    title: "Harry Potter e as Relíquias da Morte",
    subtitle: null,
    authors: ["J. K. Rowling"],
    publisher: "Rocco",
    publishedDate: new Date("2007-07-01T00:00:00Z"),
    isbn: "9788532515186",
    language: "Português",
    pageCount: 592,
    coverImage: "/HarryPotterReliquiasMorte",
    genres: ["Fantasia", "Infantojuvenil", "Drama", "Ação"],
    description: `A batalha final se aproxima. Sem Hogwarts como refúgio, Harry, Rony e Hermione partem em uma missão perigosa para destruir as Horcruxes. As Relíquias da Morte guiam seu destino — e o da própria magia.`,
    averageRating: 5.0,
    ratingsCount: 60,
    synopsis: `A conclusão épica de uma jornada. Sem escola, sem amigos por perto, Harry assume seu destino. Cada descoberta, cada luta o conduz ao confronto decisivo com Voldemort — e à prova final de coragem, lealdade e amor.`,
    authorBio: `(Mesmo bio)`
  },
  {
    title: "O Silmarillion",
    subtitle: null,
    authors: ["J. R. R. Tolkien"],
    publisher: "WMF Martins Fontes",
    publishedDate: new Date("2006-01-01T00:00:00Z"),
    isbn: "8533613318",
    language: "Português",
    pageCount: 460,
    coverImage: "/OSilmarillion",
    genres: ["Fantasia Épica", "Mitologia"],
    description: `Coletânea de mito-poesias que compõem a gênese do universo de Tolkien, desde a criação de Eä até a Terceira Era. Composta por Ainulindalë (a criação), Valaquenta (seres mitológicos), Quenta Silmarillion (guerras da Primeira Era), Akallabêth (queda de Númenor) e Dos Anéis de Poder e da Terceira Era. Um mergulho profundo na estrutura mitológica da Terra-média.`,
    averageRating: 4.6,
    ratingsCount: 120,
    synopsis: `Editado postumamente por Christopher Tolkien, o livro reúne lendas, genealogias e mitos que precedem O Hobbit e O Senhor dos Anéis. Serve como a “espinha dorsal” da mitologia tolkieniana, abordando a criação, o surgimento das Silmarils e as consequências traumáticas que moldaram a Terra-média.`,
    authorBio: `J. R. R. Tolkien (1892–1973) foi professor, filólogo e o criador de um dos universos de fantasia mais influentes da literatura. Sua erudição em línguas e mitologia fundamentou obras como O Hobbit e O Senhor dos Anéis — e, em extensão, toda a mitologia do Silmarillion.`
  },
  {
    title: "Beren e Lúthien",
    subtitle: null,
    authors: ["J. R. R. Tolkien (editor: Christopher Tolkien)"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2018-01-01T00:00:00Z"),
    isbn: "9788595083660",
    language: "Português",
    pageCount: 368,
    coverImage: "/BerenELuthien",
    genres: ["Fantasia Épica", "Romance Mitológico"],
    description: `Reúne diversas versões do conto épico sobre o amor impossível entre o mortal Beren e a élfica Lúthien, um dos Três Grandes Contos da Primeira Era da Terra-média. Editado por Christopher Tolkien e ricamente ilustrado por Alan Lee.`,
    averageRating: 4.9,
    ratingsCount: 4650,
    synopsis: `Christopher Tolkien apresenta versões em prosa e verso do lendário romance, revelando a evolução da narrativa ao longo das décadas. É uma obra emotiva e simbólica — Tolkien chegou a homenagear sua esposa, Lúthien, gravando seu nome em seu túmulo.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "A Queda de Gondolin",
    subtitle: null,
    authors: ["J. R. R. Tolkien (editor: Christopher Tolkien)"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2018-01-01T00:00:00Z"),
    isbn: "8595083657",
    language: "Português",
    pageCount: 320,
    coverImage: "/AQuedaDeGondolin",
    genres: ["Fantasia Épica", "Tragédia"],
    description: `Terceiro dos “Grandes Contos Perdidos”, narra a jornada de Tuor à cidade élfica de Gondolin e sua queda trágica. Publicado com ilustrações de Alan Lee e edição comentada por Christopher Tolkien.`,
    averageRating: 4.8,
    ratingsCount: 800,
    synopsis: `A jornada misteriosa e solitária de Tuor culmina na perda de Gondolin, cidade sagrada, diante das forças de Morgoth — uma narrativa épica e melancólica que aprofunda a Primeira Era da Terra-média.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "Contos Inacabados de Númenor e da Terra-média",
    subtitle: null,
    authors: ["J. R. R. Tolkien (editor: Christopher Tolkien)"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2020-01-01T00:00:00Z"),
    isbn: "9788595085701",
    language: "Português",
    pageCount: 624,
    coverImage: "/ContosInacabados",
    genres: ["Fantasia Épica", "Ensaios Narrativos"],
    description: `Coletânea que abrange narrativas complexas desde a Primeira à Terceira Era: histórias de Rohan, Númenor, Palantíri, os Cinco Magos, entre outras. São textos revisados e contextualizados por Christopher Tolkien, com mapas inéditos.`,
    averageRating: 4.7,
    ratingsCount: 300,
    synopsis: `Uma obra indispensável para quem deseja compreender os bastidores da Terra-média: são contos fragmentados, mas essenciais para preencher lacunas, entender lendas e costumes que moldaram os eventos principais.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "A Queda de Númenor: e outros contos da Segunda Era da Terra-média",
    subtitle: null,
    authors: ["J. R. R. Tolkien (editor: Brian Sibley)"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2022-01-01T00:00:00Z"),
    isbn: "6555113987",
    language: "Português",
    pageCount: 336,
    coverImage: "/AQuedaDeNumenor",
    genres: ["Fantasia Épica", "Segunda Era"],
    description: `Narrativa linear dos principais acontecimentos da Segunda Era — desde a queda de Númenor até a Última Aliança. Organizada por Brian Sibley com base em relatos de Tolkien e enriquecida com ilustrações de Alan Lee.`,
    averageRating: 4.7,
    ratingsCount: 150,
    synopsis: `Uma abordagem cronológica que facilita o entendimento dos eventos que antecedem O Senhor dos Anéis — ideal para fãs da série de TV “Anéis de Poder” e para estudo estruturado da Terceira Era.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "O Hobbit",
    subtitle: null,
    authors: ["J. R. R. Tolkien"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2019-01-01T00:00:00Z"),
    isbn: "9788595084759-1",
    language: "Português",
    pageCount: 316,
    coverImage: "/OHobbit",
    genres: ["Fantasia Infantil", "Aventura"],
    description: `Aventura inaugural da Terra-média: Bilbo Bolseiro é convencido por Gandalf a participar de uma jornada com treze anões para recuperar um tesouro guardado por um dragão. Um clássico que combina humor, coragem e descoberta.`,
    averageRating: 4.8,
    ratingsCount: 1200,
    synopsis: `Uma jornada épica com trolls, elfos, Gollum e um dragão — Bilbo descobre sua coragem e engendra a aventura que desencadearia as sagas seguintes.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    subtitle: null,
    authors: ["J. R. R. Tolkien"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2019-01-01T00:00:00Z"),
    isbn: "9788595084759-2",
    language: "Português",
    pageCount: 480,
    coverImage: "/SociedadeDoAnel",
    genres: ["Fantasia Épica", "Alta Fantasia"],
    description: `Primeiro volume da trilogia que segue Frodo e seus companheiros em busca de destruir o Um Anel. Lançamento da nova tradução HarperCollins, que substituiu a versão anterior da Martins Fontes.`,
    averageRating: 4.9,
    ratingsCount: 2000,
    synopsis: `Uma aliança improvável forma-se — hobbits, homens, elfos, anões e magos enfrentam perigos diversos em uma missão que determinará o destino da Terra-média.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "O Senhor dos Anéis: As Duas Torres",
    subtitle: null,
    authors: ["J. R. R. Tolkien"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2019-01-01T00:00:00Z"),
    isbn: "9788595084766",
    language: "Português",
    pageCount: 480,
    coverImage: "/AsDuasTorres",
    genres: ["Fantasia Épica", "Alta Fantasia"],
    description: `Continuação da saga — Frodo e Sam avançam em direção a Mordor enquanto Aragorn, Legolas e Gimli enfrentam desafios épicos. Edição HarperCollins com tradução atualizada.`,
    averageRating: 4.9,
    ratingsCount: 1900,
    synopsis: `A luta contra o mal se intensifica — alianças são certas, traições acontecem e o peso da missão pesa cada vez mais.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "O Senhor dos Anéis: O Retorno do Rei",
    subtitle: null,
    authors: ["J. R. R. Tolkien"],
    publisher: "HarperCollins Brasil",
    publishedDate: new Date("2019-01-01T00:00:00Z"),
    isbn: "9788595084773",
    language: "Português",
    pageCount: 480,
    coverImage: "/RetornoDoRei",
    genres: ["Fantasia Épica", "Alta Fantasia"],
    description: `Conclusão grandiosa da jornada — com batalhas decisivas, sacrifícios e a restauração do equilíbrio na Terra-média. Edição HarperCollins Brasil com tradução moderna.`,
    averageRating: 5.0,
    ratingsCount: 2100,
    synopsis: `O ápice da luta épica: o destino de muitos é decidido, o legado é reafirmado e a era chega ao fim — numa história de coragem, amizade e esperança.`,
    authorBio: `(Mesmo bio anterior)`
  },
  {
    title: "Trono de Vidro",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2013-08-27T00:00:00.000Z",
    isbn: "9788501090751",
    language: "Português",
    pageCount: 392,
    coverImage: "/TronoDeVidro",
    genres: [
      "Fantasia",
      "Juvenil"
    ],
    description: "Celaena Sardothien, a assassina mais temida de Adarlan, é libertada das minas de sal de Endovier para competir em um torneio que decidirá o novo campeão do rei. Mas em meio ao desafio, segredos sombrios e uma ameaça mortal emergem, colocando sua vida e seu futuro em risco.",
    averageRating: 4.9,
    ratingsCount: 5800,
    synopsis: "Aos 18 anos, Celaena recebe a chance de sua vida: lutar em um torneio para ganhar sua liberdade e tornar-se campeã do rei. Enquanto enfrenta adversários brutais, descobre segredos em castelo cheio de magia antiga e corrupção.",
    authorBio: "Sarah J. Maas é uma escritora norte-americana de fantasia, conhecida por suas séries Trono de Vidro e Corte de Espinhos e Rosas. Seus livros já foram traduzidos para dezenas de idiomas e conquistaram milhões de leitores ao redor do mundo."
  },
  {
    title: "Coroa da Meia-Noite",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2013-08-27T00:00:00.000Z",
    isbn: "9788501091215",
    language: "Português",
    pageCount: 448,
    coverImage: "/CoroaDaMeiaNoite",
    genres: [
      "Fantasia",
      "Juvenil"
    ],
    description: "Após conquistar o título de campeã do rei, Celaena deve servir ao trono que despreza. Dividida entre sua lealdade e sua consciência, ela descobre conspirações que ameaçam derrubar o reino e uma verdade sombria sobre sua própria herança.",
    averageRating: 4.9,
    ratingsCount: 5100,
    synopsis: "Celaena cumpre sua função como campeã do rei, mas usa astúcia para sabotar ordens cruéis. Entre alianças frágeis e traições, descobre um segredo capaz de mudar tudo o que acreditava sobre si mesma e sobre o futuro de Adarlan.",
    authorBio: "Sarah J. Maas é uma escritora norte-americana de fantasia, conhecida por suas séries Trono de Vidro e Corte de Espinhos e Rosas. Seus livros já foram traduzidos para dezenas de idiomas e conquistaram milhões de leitores ao redor do mundo."
  },
  {
    title: "Herdeira do Fogo",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2014-09-02T00:00:00.000Z",
    isbn: "9788501091819",
    language: "Português",
    pageCount: 648,
    coverImage: "/HerdeiraDoFogo",
    genres: [
      "Fantasia",
      "Juvenil"
    ],
    description: "Exilada em Wendlyn, Celaena precisa enfrentar seu passado e dominar seus poderes. Entre treinamento árduo e novos aliados, ela percebe que seu destino está ligado não apenas à coroa, mas ao futuro de todo o continente.",
    averageRating: 4.9,
    ratingsCount: 5600,
    synopsis: "Longe de Adarlan, Celaena descobre sua herança perdida e enfrenta inimigos mais poderosos do que jamais imaginou. Enquanto aprende a controlar sua magia, a ameaça de guerra se aproxima cada vez mais.",
    authorBio: "Sarah J. Maas é uma escritora norte-americana de fantasia, conhecida por suas séries Trono de Vidro e Corte de Espinhos e Rosas. Seus livros já foram traduzidos para dezenas de idiomas e conquistaram milhões de leitores ao redor do mundo."
  },
  {
    title: "Rainha das Sombras",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2015-09-01T00:00:00.000Z",
    isbn: "9788501103642",
    language: "Português",
    pageCount: 672,
    coverImage: "/RainhaDasSombras",
    genres: [
      "Fantasia",
      "Juvenil"
    ],
    description: "De volta a Rifthold, Celaena – agora Aelin Galathynius – luta para libertar seu povo e destruir o rei de Adarlan. O livro marca um ponto de virada em sua jornada, onde a vingança e a justiça caminham lado a lado.",
    averageRating: 4.9,
    ratingsCount: 6000,
    synopsis: "Determinada a recuperar seu trono, Aelin enfrenta inimigos políticos e sobrenaturais em Rifthold. Entre perdas devastadoras e batalhas épicas, ela descobre a verdadeira força de sua herança.",
    authorBio: "Sarah J. Maas é uma escritora norte-americana de fantasia, conhecida por suas séries Trono de Vidro e Corte de Espinhos e Rosas. Seus livros já foram traduzidos para dezenas de idiomas e conquistaram milhões de leitores ao redor do mundo."
  },
  {
    title: "Império de Tempestades",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2017-10-16T00:00:00.000Z",
    isbn: "9788501109446",
    language: "Português",
    pageCount: 658,
    coverImage: "/ImperioDeTempestades",
    genres: [
      "Fantasia",
      "Romance",
      "Young Adult"
    ],
    description: "Quinto volume da série *Trono de Vidro*, 'Império de Tempestades' mergulha em batalhas épicas, alianças frágeis e reviravoltas emocionantes. Aelin Galathynius, agora plenamente consciente de seu destino como rainha, precisa unir povos e preparar o continente para enfrentar o maior inimigo de sua era. Ao mesmo tempo, segredos do passado e jogos de poder ameaçam despedaçar tudo o que ela conquistou. É um livro sobre coragem, sacrifício e a dolorosa construção de um legado em meio ao caos.",
    averageRating: 5,
    ratingsCount: 48,
    synopsis: "Aelin enfrenta a guerra iminente contra Erawan e Maeve, enquanto precisa lidar com traições, segredos ancestrais e um futuro incerto. Para proteger Terrasen e aqueles que ama, ela é obrigada a tomar decisões devastadoras e a desafiar tanto os inimigos quanto seus próprios limites. Ao lado de aliados inesperados, a protagonista segue em uma jornada que redefinirá não apenas seu destino, mas também o futuro de todo o reino.",
    authorBio: "Sarah J. Maas é autora best-seller de fantasia, conhecida pelas séries *Trono de Vidro*, *Corte de Espinhos e Rosas* e *Cidade da Lua Crescente*. Seus livros são marcados por personagens femininas fortes, universos detalhados e narrativas que mesclam ação, romance e temas de autodescoberta."
  },
  {
    title: "Torre do Alvorecer",
    subtitle: null,
    authors: [
      "Sarah J. Maas"
    ],
    publisher: "Galera Record",
    publishedDate: "2017-09-05T00:00:00.000Z",
    isbn: "9788501112514",
    language: "Português",
    pageCount: 658,
    coverImage: "/TorreDoAlvorecer",
    genres: [
      "Fantasia",
      "Juvenil"
    ],
    description: "Chaol Westfall viaja ao continente do sul em busca de cura e de aliados para enfrentar a guerra iminente. Entre intrigas políticas e desafios pessoais, descobre novas forças e propósitos.",
    averageRating: 4.7,
    ratingsCount: 4300,
    synopsis: "Enquanto Aelin luta no norte, Chaol e Nesryn buscam alianças no sul. Entre revelações e desafios, descobrem que a esperança pode nascer mesmo nas maiores trevas.",
    authorBio: "Sarah J. Maas é uma escritora norte-americana de fantasia, conhecida por suas séries Trono de Vidro e Corte de Espinhos e Rosas. Seus livros já foram traduzidos para dezenas de idiomas e conquistaram milhões de leitores ao redor do mundo."
  },
  {
    title: "Orgulho e Preconceito",
    subtitle: null,
    authors: ["Jane Austen"],
    publisher: "Principis (Rocco)",
    publishedDate: new Date("2018-10-01T00:00:00Z"),
    isbn: "8594318030",
    language: "Português",
    pageCount: 224,
    coverImage: "/OrgulhoPreconceito",
    genres: ["Romance", "Clássico"],
    description: `Um retrato aguçado da sociedade inglesa do século XVIII, centrado na busca por status social e emocional por meio do casamento, especialmente para mulheres sem direito à herança. Elizabeth Bennet destaca-se por sua inteligência e independência, enquanto o Sr. Darcy revela sua verdadeira nobreza por trás da fachada reservada.`,
    averageRating: 4.8,
    ratingsCount: 500,
    synopsis: `A chegada de dois jovens e atraentes vizinhos, Sr. Bingley e Sr. Darcy, desestabiliza a família Bennet. Elizabeth e Darcy começam com preconceito mútuo, mas, à medida que as tensões dissolvem, descobrem sentimentos que desafiam o orgulho e a sina de permanecerem juntos.`,
    authorBio: `Jane Austen (1775–1817) foi uma escritora inglesa que revolucionou o romance com sua ironia, análise social e heroínas autênticas. Seus seis principais romances, incluindo “Orgulho e Preconceito”, permanecem como marcos da literatura clássica.`
  },
  {
    title: "Os Sete Maridos de Evelyn Hugo",
    subtitle: null,
    authors: ["Taylor Jenkins Reid"],
    publisher: "Paralela",
    publishedDate: new Date("2019-01-01T00:00:00Z"),
    isbn: "9788584391509",
    language: "Português",
    pageCount: 360,
    coverImage: "/SeteMaridosEvelynHugo",
    genres: ["Romance", "Contemporary Fiction"],
    description: `Evelyn Hugo, lendária estrela de Hollywood, decide revelar sua “verdadeira história” à jornalista Monique Grant. Navega entre fama, amor, sacrifícios e segredos insondáveis, revelando como suas escolhas moldaram a lenda — e o preço que pagou por tudo isso.`,
    averageRating: 4.8,
    ratingsCount: 50000,
    synopsis: `Aos 79 anos, uma estrela reclusa da Velha Hollywood escolhe uma jornalista iniciante para contar sua vida — seus sete amores e casamentos tumultuados. O passado e o presente se entrelaçam conforme Monique descobre que estão mais conectadas do que imaginava.`,
    authorBio: `Taylor Jenkins Reid é autora best-seller americana, com obras aclamadas como “Daisy Jones & The Six”. Suas narrativas dramáticas e emocionais conquistaram leitores no mundo todo. Vive em Los Angeles com a família.`
  },
  {
    title: "A Hipótese do Amor",
    subtitle: null,
    authors: ["Ali Hazelwood"],
    publisher: "Arqueiro",
    publishedDate: new Date("2022-07-05T00:00:00Z"),
    isbn: "9786555653304",
    language: "Português",
    pageCount: 336,
    coverImage: "/HipoteseDoAmor",
    genres: ["Romance", "Comédia Romântica"],
    description: `Quando uma estudante de doutorado e um professor estrelam um namoro de mentirinha, o experimento, planejado para desapontar, começa a desafiar toda lógica científica — e emocional. Inteligente, engraçado e irresistível.`,
    averageRating: 4.8,
    ratingsCount: 20016,
    synopsis: `Olive Smith, obcecada por estudos e lógica, finge um relacionamento com seu antiético professor para afastar sua amiga de seu ex. Mas a ficção sai do script e desafia a ciência do amor.`,
    authorBio: `Ali Hazelwood é ex-acadêmica e hoje fenômeno da comédia romântica moderna. Tornou-se viral no TikTok e conquistou leitores com personagens acadêmicos e diálogos afiados.`
  },
  {
    title: "Verity",
    subtitle: "Edição de Colecionador",
    authors: ["Colleen Hoover"],
    publisher: "Galera Record",
    publishedDate: new Date("2024-06-10T00:00:00Z"),
    isbn: "9786559815043",
    language: "Português",
    pageCount: 360,
    coverImage: "/Verity",
    genres: ["Romance", "Thriller Psicológico"],
    description: `Romance surpreendente de Colleen Hoover, agora em edição de colecionador com capítulo extra. Um triângulo sombrio entre uma autora paralisada, seu marido e uma substituta, que revela segredos perturbadores — e um final devastador.`,
    averageRating: 4.7,
    ratingsCount: 1797,
    synopsis: `Lowen aceita terminar a série da autora Verity, incapacitada após um acidente. Ao ler seu manuscrito íntimo, descobre segredos que desafiam a sanidade — e sua própria moral. Thriller envolvente com reviravoltas impiedosas.`,
    authorBio: `Colleen Hoover é autora best-seller de romances e suspense emocional. Suas obras viralizam no BookTok e exploram o lado mais íntimo das relações humanas.`
  },
  {
    title: "É assim que acaba",
    subtitle: null,
    authors: ["Colleen Hoover"],
    publisher: "Galera Record",
    publishedDate: new Date("2020-01-01T00:00:00Z"),
    isbn: "9780000000001",
    language: "Português",
    pageCount: 320,
    coverImage: "/EAsimQueAcaba",
    genres: ["Romance", "Drama"],
    description: `Colleen Hoover mergulha em um relacionamento abusivo através dos olhos de Lily, cuja vontade de resistir é testada pelo amor e pela violência doméstica. Um drama comovente, controverso e impactante.`,
    averageRating: null,
    ratingsCount: null,
    synopsis: `Lily inicia um namoro com Ryle, médico encantador que se mostra perigoso nas entrelinhas. Sua força e apoio vêm da amiga Atlas — mas até onde é possível amar alguém que machuca? Romance cru e realista.`,
    authorBio: `Colleen Hoover é autora best-seller de romances e suspense emocional. Suas obras viralizam no BookTok e exploram o lado mais íntimo das relações humanas.`
  },
  {
    title: "Hamlet",
    subtitle: null,
    authors: ["William Shakespeare"],
    publisher: "(várias edições)",
    publishedDate: null,
    isbn: "hamlet-unique-id-001",
    language: "Inglês",
    pageCount: null,
    coverImage: "/Hamlet",
    genres: ["Drama", "Tragédia"],
    description: `Uma das peças mais profundas da literatura ocidental, “Hamlet” explora temas de vingança, loucura, moralidade e o destino. O príncipe da Dinamarca enfrenta dilemas éticos e existenciais após a morte de seu pai — e um fantasma exigindo justiça.`,
    averageRating: null,
    ratingsCount: null,
    synopsis: `O príncipe Hamlet busca vingar o assassinato do pai, confrontando traição, loucura — real ou fingida — e conspirações na corte. Um retrato imortal da condição humana e do poder corruptor da ambição.`,
    authorBio: `William Shakespeare (1564–1616), o dramaturgo britânico mais influente da literatura, cujas tragédias e comédias moldaram gerações e continuam a ressoar no mundo todo.`
  },
  {
    title: "It – A Coisa",
    subtitle: null,
    authors: ["Stephen King"],
    publisher: "Suma de Letras",
    publishedDate: new Date("2014-07-24T00:00:00Z"),
    isbn: "9788560280940",
    language: "Português",
    pageCount: 1104,
    coverImage: "/ItACoisa",
    genres: ["Terror", "Horror", "Ficção sobrenatural"],
    description: `Um dos romances mais densos de Stephen King: sete amigos enfrentam uma entidade maléfica e mutável que assume a forma mais aterradora possível, explodindo traumas e lembranças dolorosas. Alternando entre infância e vida adulta, a narrativa reflete sobre a memória, amizade e os terrores que carregamos — e como enfrentá-los.`,
    averageRating: 4.7,
    ratingsCount: 3000,
    synopsis: `Primeiro ambientado em 1958, em Derry, crianças enfrentam visões horripilantes e descobrem que compartilham o mesmo pesadelo: a Coisa. Décadas depois, já adultos, são convocados a retornar quando a entidade retorna. Só a união deles pode quebrar esse ciclo de medo.`,
    authorBio: `Stephen King, mestre do terror contemporâneo, escreveu mais de 60 romances e coleções de contos. Seu estilo combina o horror do cotidiano com atmosferas sobrenaturais — tornando-o uma referência global no gênero.`
  },
  {
    title: "Frankenstein",
    subtitle: null,
    authors: ["Mary Shelley"],
    publisher: "Penguin Companhia / DarkSide",
    publishedDate: new Date("2018-01-01T00:00:00Z"),
    isbn: "9788520937122",
    language: "Português",
    pageCount: 304,
    coverImage: "/Frankenstein",
    genres: ["Terror", "Ficção Gótica", "Clássico"],
    description: `O romance seminal que introduziu o arquétipo do “monstro” criado pelo homem. Navegando entre ciência, ambição e ética, a narrativa traz Victor Frankenstein, um cientista obcecado pela vida — e a criatura resultante de sua arrogância.`,
    averageRating: 4.5,
    ratingsCount: 1200,
    synopsis: `Victor Frankenstein cria vida — mas a criatura que nasce é abandonada. Rejeitada e isolada, ela busca vingança contra seu criador. Um confronto moral e existencial se desenrola entre criador e criatura, entre a compaixão e a monstruosidade.`,
    authorBio: `Mary Shelley (1797–1851) escreveu “Frankenstein” aos 18 anos, criando um dos símbolos mais duradouros da literatura gótica e de horror. O romance reflete seu contexto romântico, preocupações científicas e questionamentos éticos.`
  },
];


async function main() {
  await prisma.book.createMany({ data: books });
  console.log("✅ Seed inserido com sucesso: ", books.length, "livros.");
}

main()
  .catch((e) => {
    console.error("❌ Erro ao executar seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
